### PR TITLE
Add CI framework

### PR DESCRIPTION
**Pull request by jeking3**
This pull requests integrates this code repository with various continuous integration tools. 

  - travis with valgrind, cppcheck, ubsan, codecov, covscan (future)
  - appveyor with MSVC 2010 through 2017, cygwin 32/64, mingw 32/64
  - README, LICENSE, etc.

This is based on the work in boost-ci, found at https://github.com/boostorg/boost-ci.  This work aims to make code submissions higher quality and detect issues before code is submitted to `develop`.  This means authors, maintainers, bug fixers are encourages to submit pull requests for all their changes, and let the CI build verify they are good before merging.

To take advantage of this a number of steps have to be taken by an admin on this repository to enable Travis CI and Appveyor.  Since these are not currently enabled on this repository, I built this pull request on my fork where it is integrated:

AppVeyor: https://ci.appveyor.com/project/jeking3/contract/builds/25032326
Travis CI: https://travis-ci.org/jeking3/contract/builds/541239458

If you are interested I can help configure and maintain these tools for you, but it would require granting me admin access to set this up.  I am on the Boost CMT.

There are a number of known failures; if these are never going to be fixed (like gcc 4.8 and 4.9) they can be removed from the build.  I already removed MSVC 2010 and 2012, but I left MSVC 2013 because it looks like a new issue.  Valgrind was fixed, but I guess that broke gcc 5 builds, so that was fixed and now valgrind is broken again.  The CI framework will help avoid these "whack a mole" scenarios if changes go in through pull requests.

### CODE REVIEW

**Comment by jeking3** [comment]
Sorry, closed the wrong one!  Wanted to close my fork's PR.

**Comment by jeking3** [comment]
Sorry, the closing and opening caused a duplicate build in the travis.com account; Build #2 is a duplicate of Build #3.  You can cancel Build #2 to free up some resources.

**Comment by lcaminiti** [comment]
I looked at the pull request. This all new stuff to me... but it looks good. Before I merge it to develop, I would like to confirm:
Will this pull request run CI on example/* or just test/*?

**Comment by jeking3** [comment]
It runs b2 on the top level Jamfile and I disabled examples/ in there.

**Pull request merged**
